### ISSUE TITLE
Icon is blank

### ISSUE THREAD

**Issue by GFialho** [0xsequence/rainbowkit-plugin#9] opened 2023-09-06 15:13 UTC
Icon is not showing on rainbowkit:
![image](https://github.com/0xsequence/rainbowkit-plugin/assets/108136415/2405ce08-c969-4971-8b7e-3f695e1832dd)

You can check on the live demo page: https://0xsequence.github.io/demo-dapp-rainbowkit/

**Comment by pkieltyka** [comment] 2023-09-06 15:29
thanks for the heads up -- we'll fix this in a few min :)

**Comment by SebastianJ21** [comment] 2023-09-06 15:33
Was just about to submit a PR for you :)

The issue is just a missing semicolon in the `const icon`:

```
`data:image/svg+xmlbase64,` -> `data:image/svg+xml;base64,`
```

**Comment by pkieltyka** [comment] 2023-09-06 16:58
thanks :)

**Comment by pkieltyka** [comment] 2023-09-06 17:02
resolved in v2.1.4 :)

**Closed as completed by pkieltyka** 2023-09-06 17:02 UTC
